import "./globals.css";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import Script from "next/script";
import DesktopHeader from "../components/header";
import Sidebar from "../components/sidebar";
import Miniplayer from "../components/Miniplayer";
import SettingJson from '../context/Provider';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Yoth",
  description: "Generated by create next app",
};

export default function RootLayout({ children, ...a }) {
  const headersList = headers();

  const referer = new URL(
    headersList.get("next-url"),
    "https://" + headersList.get("host")
  );

  var _,
    t,
    theme = referer?.searchParams.get("theme");
  switch (theme) {
    case 0:
      t = true;
      break;
    case 1:
      _ = true;
      break;
    case 2:
      _ = false;
      break;
    default:
      _ = false;
  }
  const darkHeader = true;
  const dark = _;
  const hideHeaderBorderBottom = true;
  const rerenderAfterLogin = true;
  const ling =
    referer.searchParams.get("ling") ||
    parseLanguagePreferences(headersList.get("accept-language"))[0]?.code;
  const loggedUID = 83583758364;
  const bg = {};
  const head_props = t
    ? {}
    : dark
    ? { className: "dark" }
    : { className: "light" };
  return (
    <html lang={ling} {...head_props}>
      <body className={inter.className}>
      <SettingJson>
        <div id="app-desktop">
          <Miniplayer />
          <div className="desktop-layout desktop">
            <DesktopHeader />
            <Sidebar />
            <div className="layout-content-wrapper">
              <div className="layout-content">{children}</div>
            </div>
          </div>
        </div>
      </SettingJson>
      </body>
    </html>
  );
  //    <Script src="/s/player/en/base.js" />
}
function parseLanguagePreferences(preferences) {
  const languageArray = preferences.split(",").map((item) => {
    const [code, priority] = item.trim().split(";q=");
    return { code, priority: parseFloat(priority) || 1 };
  });

  return languageArray;
}
