import Script from "next/script";
import { Inter } from "next/font/google";
import "./globals.css";
import DesktopHeader from "../components/header";
import Sidebar from "../components/sidebar";
import Miniplayer from "../components/Miniplayer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  const darkHeader = true;
  const hideHeaderBorderBottom = true;
  const rerenderAfterLogin = true;
  const loggedUID = 83583758364;
  const bg = {};

  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="app-desktop">
          <Miniplayer />
          <div className="desktop-layout desktop" style={bg}>
            <DesktopHeader bg={darkHeader || !bg ? "dark" : "transparent"} />
            <Sidebar />
            <div className="layout-content-wrapper">
              <div
                className="layout-content"
                id="layout-content"
                data-infinite-scrollable
                key={rerenderAfterLogin ? loggedUID : "layout-content"}
              >
                {children}
              </div>
            </div>
          </div>
        </div>
        <Script src="/s/player/en/base.js" />
      </body>
    </html>
  );
}
